{% set name = "cadquery" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CadQuery/cadquery/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9a71a3bb1185228f62b14810fe078489f4af61e02d9e2c683e68626ff9903dbc

build:
  number: 0
  noarch: python
  script: python -m pip install -vv --no-deps --ignore-requires-python --ignore-installed .

requirements:
  host:
    - python >=3.8,<=3.11
    - pip
  run:
    - python >=3.8,<=3.11
    - ocp 7.7.*
    - pyparsing >=2.1.9
    - ezdxf
    - ipython
    - typing_extensions
    - nptyping >=2.0.1
    - nlopt
    - multimethod >=1.7,<2.0
    - casadi

test:
  requires:
    - pytest
    - docutils
    - path
    - pip
  source_files:
    - tests/
  commands:
    - pip check
    - pytest -vv

about:
  home: https://github.com/cadquery/cadquery
  license: Apache-2.0
  license_family: Apache
  license_file: src/LICENSE
  summary: |
    CadQuery is a parametric scripting language for creating and traversing
    CAD models
  description: |
    CadQuery is an intuitive, easy-to-use python library for building
    parametric 3D CAD models. It has several goals:
    - Build models with scripts that are as close as possible to how you’d
      describe the object to a human, using a standard, already established
      programming language
    - Create parametric models that can be very easily customized by end users
    - Output high quality CAD formats like STEP and AMF in addition to
      traditional STL
    - Provide a non-proprietary, plain text model format that can be edited and
      executed with only a web browser
  doc_url: https://cadquery.readthedocs.io/
  dev_url: https://github.com/cadquery/cadquery

extra:
  recipe-maintainers:
    - bollwyvl
    - adam-urbanczyk
