{% set name = "cadquery" %}
{% set version = "1.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: b2ddd927cb81bc9ad2332692d4ab0b4cb36581543463b64bd2d388b3709ea0ae
    patches:
      - osx_freecad_path.patch
  - folder: src
    url: https://github.com/dcowden/cadquery/archive/v{{ version }}.tar.gz
    sha256: 75eb6f987aeaf3d86197353c53dc2808a78fa9f2ade651f5751e96aa14b23829

build:
  number: 0
  noarch: python
  script: cd dist && python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.6,<3.7
    - pip
  run:
    - python >=3.6,<3.7
    - pyparsing
    - freecad

test:
  source_files:
    - src/tests
    - src/runtests.py
  requires:
    - mock
  imports:
    - cadquery
  commands:
    - cd src
    - python runtests.py

about:
  home: https://github.com/dcowden/cadquery
  license: Apache-2.0
  license_family: Apache
  license_file: src/LICENSE
  summary: |
    CadQuery is a parametric scripting language for creating and traversing
    CAD models
  description: |
    CadQuery is an intuitive, easy-to-use python library for building
    parametric 3D CAD models. It has several goals:
    - Build models with scripts that are as close as possible to how you’d
      describe the object to a human, using a standard, already established
      programming language
    - Create parametric models that can be very easily customized by end users
    - Output high quality CAD formats like STEP and AMF in addition to
      traditional STL
    - Provide a non-proprietary, plain text model format that can be edited and
      executed with only a web browser
  doc_url: http://dcowden.github.io/cadquery/
  dev_url: https://github.com/dcowden/cadquery

extra:
  recipe-maintainers:
    - bollwyvl
