travis:
  secure:
    BINSTAR_TOKEN: bl7OK3GpaiC4mlbqfesj5xuM2ScSeVU/ykHqPohQbMc6Jn6pK9Ik//YN0854SR9k//LtnqIXA/7HgyGIrXutK87WFOPxg8KQQjOhCmVJ8icDQAZNIZSZjNYuyzshVNbz5bhEdQ0B4jrik8mYyXxbAFDouSUmFbz7G+GpDWiR0jhr+zhLDzr4EZnVbaTQoNaSrz6swsmiphB/rbo1y8WaMR7SlxEC4InmgHQwS/oYfElEwRIksDLX2yfEVrzWE+FOVtFjwVISTze9CV/a20N/kJiBGCiK8ZUjR917mhBD8DxHh6QdfosveQyo/2ys95pi1/79MCpYciEwlD9CRdXVZ4G3NuLzl4F2OwW6V9F/F22Y3rWKiBmd83Q53F+rhJNn02RhbibXRBevE4pXB2OsLTqZp29NXOd0bKUWMVXS6yCbA0Q0g+gIUY97JR3lS8AL4Hd13mAvbc+L4AYqaSdasmrgR4HdZNbkcSlReSEQMckyypBULbi0D/WwPg+yFiOhjvjFgEfDCftf7fOYRgv2uxfXt157KebtKt8yh9xrjR6vz/i5XbW0E1TtYqZKcjNpNRuCfgfGbjBormOhANr5ZFlkyQwsAawVtzmutFk3A0SeNYH5aBDB4Ro/Ll9j/XkmBNLWWIXJ0ZZMhJOlHMFHB7hYvHRjgGSa12oY2RyC6DU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
