travis:
  secure:
    BINSTAR_TOKEN: pJTBq4dq4YD5lINlAvo9OFEJoxOIWRWPMKETackW8xbxhrsxzIsSIi46uTEx+zNhnTS32MLSLFS63T3qm8pbjSfXWn/sWNInI06aXEob5ZzhC1GLwaqX4Mdo/iZyVB/9NiTnlLLDL2VJoqsKLLN84FW42uUwSUQHRndONwHWo43hxpYWJIp5LF6YljWPgDQavBtCQa7e/A56nHk0qv96jVDh7vh+ma81Nsm2op5QRCRYduNbmUGuJ/LizwLe2BnwvGtkybVs/+8I1ie8YuOfJWVzdk335rKKeh2ew+l3kCvQ33Bw3W3iEywhsW8xhPgslCpyL/S40iGuZoEyOLa0g/WE+8z+Qm2ot/UsLdE738vxVfW5yS6Bo0+LxgMoga6Qjza5gfmaoXSCMsAN3nM188MyKEwrsGNOmQt/n0liBSSqSMQbzA4Gt8fcl8w1jEst/EUaAQPPoKaaB7c3MHzZeLlW9wcxWLsX8Q9fFWcYL8gJbww8fGl1e08+ilYo0kH5wH/LNm5bjdxAdLR5KylaBmZw7e0+boEoyrgXpMUE5hIR/+FztIYqYPRYgn6tWXOlfHs/P/4thWO3mB4BsRr64m0vyJ9DincEPYkg/zgnZP26LG12eOZ89Y8NPRbHmV7fSzCYCn18+xlGgniH/W/KOLt+Gj3mUVpbIdOaT30H2eU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
